project:
  type: book
  preview:
    watch-inputs: true
    navigate: true


book:
  title: "Matematika untuk Pendidikan Tinggi Vokasi"
  author: "Walidatush Sholihah, Nur Aziezah, Lia Yuliawati"
  date: "2/12/2026"
  #site-url: 
  #repo-url: 
  chapters:
    - index.qmd
    - part: "Materi"
      chapters: 
        - 01-matriks.qmd
        - 02-spl.qmd
        - 03-ketaksamaan.qmd
        - 04-fungsi.qmd
        - 05-limit.qmd
        - 06-turunan.qmd
        - 07-integral.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    live-reload: true
    number-sections: true
    number-depth: 3
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    toc-expand: true
    sidebar:
      style: "docked"
      search: true
      collapse-level: 2
    theme:
      - cosmo
      - brand
  #pdf:
   # documentclass: scrreprt



